name: .NET Build Test and Docker Deploy

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main, develop ]
    types: [synchronize]


jobs:
  build:
    name: Build .Net
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          include-prerelease: True
          dotnet-version: '7.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  version:
    name: Bump version on Stable Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            include-prerelease: True
            dotnet-version: '7.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Bump versions
        uses: ThomasEg/dotnet-bump-version@patch-1
        with:
          version_files: KavitaEmail/KavitaEmail.csproj
          github_token: ${{ secrets.REPO_GHA_PAT }}

      - uses: actions/upload-artifact@v2
        with:
          name: csproj
          path: KavitaEmail/KavitaEmail.csproj
  stable:
    name: Build Docker and push
    needs: [ version ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:

      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.0.2
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse PR body
        id: parse-body
        run: |
          body="${{ steps.findPr.outputs.body }}"
          if [[ ${#body} -gt 1870 ]] ; then
            body=${body:0:1870}
            body="${body}...and much more.

            Read full changelog: https://github.com/Kareadita/KavitaEmail/pull/${{ steps.findPr.outputs.pr }}"
          fi

          body=${body//\'/}
          body=${body//'%'/'%25'}
          body=${body//$'\n'/'%0A'}
          body=${body//$'\r'/'%0D'}
          body=${body//$'`'/'%60'}
          body=${body//$'>'/'%3E'}
          echo $body
          echo "::set-output name=BODY::$body"

      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get csproj Version
        uses: naminodarie/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: KavitaEmail/KavitaEmail.csproj

      - name: Echo csproj version
        run: echo "${{steps.get-version.outputs.assembly-version}}"

      - name: Parse Version
        run: |
          version='${{steps.get-version.outputs.assembly-version}}'
          newVersion=${version%.*}
          echo $newVersion
          echo "::set-output name=VERSION::$newVersion"
        id: parse-version

      - name: Compile dotnet app
        uses: actions/setup-dotnet@v1
        with:
          include-prerelease: True
          dotnet-version: '7.0'
      - run: ./build.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: jvmilazz0/kavitaemail:latest, jvmilazz0/kavitaemail:${{ steps.parse-version.outputs.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            description: v${{steps.get-version.outputs.assembly-version}} - ${{ steps.findPr.outputs.title }}
            details: '${{ steps.parse-body.outputs.BODY }}'
            text: <@&950058626658234398> KavitaEmail ${{steps.get-version.outputs.assembly-version}} has been released.
            webhookUrl: ${{ secrets.DISCORD_DOCKER_UPDATE_URL }}
